export const DISHES_QUERY = 'DISHES_QUERY';
export const TAGS_QUERY = 'TAGS_QUERY';
export const TAGS_WITH_CONTENT_QUERY = 'TAGS_WITH_CONTENT_QUERY';
export const DISHES_NAMES_QUERY = 'DISHES_NAMES_QUERY';
export const DISH_QUERY = 'DISH_QUERY';
