export const DISHES_QUERY = 'DISHES_QUERY';
export const DISHES_NAMES_QUERY = 'DISHES_NAMES_QUERY';
export const DISH_QUERY = 'DISH_QUERY';
export const LATEST_DISH_QUERY = 'LATEST_DISH_QUERY';
export const RANDOM_DISHES_QUERY = 'RANDOM_DISHES_QUERY';
export const MENU_INGREDIENTS_QUERY = 'MENU_INGREDIENTS_QUERY';

export const TAGS_QUERY = 'TAGS_QUERY';
export const ALL_TAGS_QUERY = 'ALL_TAGS_QUERY';
export const TAGS_WITH_CONTENT_QUERY = 'TAGS_WITH_CONTENT_QUERY';
